### ISSUE TITLE
Highlighting Isnt Working on Latest Update

### ISSUE THREAD

**Issue by Ahmad-E-Nabeel** [JustusAdam/language-haskell#209] opened 2022-03-15 15:36 UTC
For some reason the highlighting doesn't work on the update that came out 22 hrs ago.

When I downgraded to 3.4.0, the highlighting came back. 

Please fix as soon as possible, Thanks!

**Comment by zacwood9** [comment] 2022-03-15 17:16
Duplicate of #208

**Closed** 2022-03-15 20:20 UTC
