### ISSUE TITLE
Variable names ending with apostrophe (') are not highlighted correctly when variable name is also a keyword

### ISSUE THREAD

**Issue by allansson** [JustusAdam/language-haskell#32] opened 2017-06-27 15:16 UTC
Some code I am working in is using a function called `module'`, but this severely messes up the syntax highlighting. 

![image](https://user-images.githubusercontent.com/2014167/27595079-ed60293e-5b5b-11e7-950a-916cc91991f4.png)

The reason is that all keywords in the grammar file is using `\b` to detect whole words. As I gather it, the `\b` will match any `\w` up until `\W`, where `\w` is a shorthand for `[a-zA-Z0-9_]` and `\W` is anything but `\w`. This is in conflict with Haskell's syntax, which actually allows any variable definition to end with `'`. I did a quick hack where I replaced the ending `\b` for the `module`-keyword with the following non-capturing group and it fixed the issue: `(?:[^a-zA-Z0-9_'])`

![image](https://user-images.githubusercontent.com/2014167/27595180-42c32c6e-5b5c-11e7-8b81-483083f6038d.png)

This problem is certainly affecting all keywords, and I was considering doing a pull request but my textmate grammar skills aren't that great so it is hard for me to know what the impact would be.

**Comment by JustusAdam** [comment] 2017-06-27 19:56
This is a duplicate of #31 

To avoid more people opening this issue as well I will publish version 2.2.2 right now which contains this fix and more.

**Closed by JustusAdam** 2017-06-27 19:56 UTC

**Comment by JustusAdam** [comment] 2017-06-27 20:12
The new version should fix it for all keywords such as `instance`, `module`, `class`, `let`, `where` etc. 
If you notice one that is still not correct please tell me, perhaps I forgot one.

**Comment by allansson** [comment] 2017-06-27 20:47
@JustusAdam Thank you! I did a search, but only among open issues. Sorry for the trouble. I will try the new version and comment in #31 if I find any errors. Great work on this extension!

**Comment by JustusAdam** [comment] 2017-06-28 09:07
I understand. You assumed that if it was a closed issue it would have been fixed in the extension as well. I was going to publish the change soon anyways. It just was an unfortunate timing.
