### ISSUE TITLE
Double colons can't be preceded by more than one space in data types

### ISSUE THREAD

**Issue by dktn** [JustusAdam/language-haskell#154] opened 2020-05-04 21:37 UTC
In current syntax highlighting schema data types are displayed wrongly - only those preceded by exactly one space gain the proper color:

![image](https://user-images.githubusercontent.com/3401063/81015849-b05acf00-8e5f-11ea-8e2f-5a84f1a499a2.png)

Aligning double colons for types clarity is often a common practice, so the situation happens frequently in some projects.

**Comment by sheaf** [comment] 2020-05-04 21:43
Thanks for the bug report.

This is a duplicate of #118, and has been fixed in 8f1b059. We'll be looking to make a new release soon (still one or two issues that need ironing out).

**Closed by sheaf** 2020-05-04 21:43 UTC
Labels: bug, duplicate, regression
