### ISSUE TITLE
v3.2.0 freezes when editing a datatype

### ISSUE THREAD

**Issue by pepeiborra** [JustusAdam/language-haskell#161] opened 2020-05-13 10:55 UTC
In my case the datatype is something like:

```
data BenchResult costs = BenchResult costs
```

This was working fine with 3.0.3. I cannot seem to figure out how to rollback, since I'm also using ghcide and VSCode refuses to use an older version of language-haskell with ghcide.

The only special thing about my setup is that I'm using the VSCode remoting SSH plugin.

**Comment by sheaf** [comment] 2020-05-13 11:01
Thanks for the bug report.
Is there any chance you could share the full datatype definition that causes the issue, and what editing action specifically causes a problem?    

I have noticed an issue which has to do with the regex engine in VS Code having some problems with recursive calls, which I reported [here](https://github.com/microsoft/vscode/issues/97238). However they did update the regex engine in the latest update (version 1.45, april 2020), and on my end that has significantly mitigated the problem.

**Comment by pepeiborra** [comment] 2020-05-13 15:05
The datatype definition was really what I shared above, in the context of a medium sized module. I am still using 1.44 here, perhaps it’s better with 1.45

**Comment by sheaf** [comment] 2020-05-13 15:26
I was able to reproduce with the following file:

```haskell
data BenchResult 

instance ( Aaaaaaaaaa x ) where
instance ( Aaaaaaaaaa x ) where
instance ( Aaaaaaaaaa x ) where
instance ( Aaaaaaaaaa x ) where
instance ( Aaaaaaaaaa x ) where
instance ( Aaaaaaaaaa x ) where
instance ( Aaaaaaaaaa x ) where
instance ( Aaaaaaaaaa x ) where
instance ( Aaaaaaaaaa x ) where
instance ( Aaaaaaaaaa x ) where
instance ( Aaaaaaaaaa x ) where
instance ( Aaaaaaaaaa x ) where
instance ( Aaaaaaaaaa x ) where
instance ( Aaaaaaaaaa x ) where
instance ( Aaaaaaaaaa x ) where
instance ( Aaaaaaaaaa x ) where
instance ( Aaaaaaaaaa x ) where
instance ( Aaaaaaaaaa x ) where
instance ( Aaaaaaaaaa x ) where
instance ( Aaaaaaaaaa x ) where
instance ( Aaaaaaaaaa x ) where
instance ( Aaaaaaaaaa x ) where
instance ( Aaaaaaaaaa x ) where
instance ( Aaaaaaaaaa x ) where
instance ( Aaaaaaaaaa x ) where
instance ( Aaaaaaaaaa x ) where
instance ( Aaaaaaaaaa x ) where
instance ( Aaaaaaaaaa x ) where
instance ( Aaaaaaaaaa x ) where
instance ( Aaaaaaaaaa x ) where
```

Typing an equals sign just after `data BenchResult` should cause the syntax highlighting to update really slowly. For some reason this happens with `Aaaaaaaaaa` being at least 10 characters long; when it is 9 characters or less the issue is significantly less severe.    

I'm investigating the issue at the moment; I will let you know when I have more info. Thanks for your patience.

**Comment by sheaf** [comment] 2020-05-13 15:58
It seems the regex for highlighting a data constructor was backtracking excessively (on top of the already slow performance of recursive calls in VS Code that I alluded to above). 

I've pushed a fix in 1bb6423, which on my end eliminates the slowness completely.

@JustusAdam I think we should cut a new release, as this can be very frustrating.

**Comment by sheaf** [comment] 2020-05-13 16:06
@pepeiborra In case you don't want to wait for a new release, you can replace your `haskell.json` file, [located at](https://vscode-docs.readthedocs.io/en/stable/extensions/install-extension/) `$home/.vscode/extensions/justusadam.language-haskell-v3.2.0/syntaxes/haskell.json`, with the following one which includes the aforementioned patch:
[haskell.json.gz](https://github.com/JustusAdam/language-haskell/files/4623173/haskell.json.gz)

Let me know if that fixes the problem on your end and we can go ahead with a new release. Thanks and sorry for the inconvenience.

**Comment by pepeiborra** [comment] 2020-05-13 17:29
Thanks for the quick response! Will give it a go tomorrow and confirm here.

**Comment by pepeiborra** [comment] 2020-05-14 14:36
I updated back to v3.2.0 today but was unable to reproduce the problem, so I have no useful info to report. Nothing else has changed, yesterday it was 100% reproducible, today it just doesn't happen. I am perplexed.

**Comment by JustusAdam** [comment] 2020-05-15 18:25
I am glad to hear that it has gotten better for you.

But just in case, I agree with you @sheaf, I'll publish a patch, just to be sure it doesn't affect more people.

**Comment by JustusAdam** [comment] 2020-05-15 18:34
Hopefully the release fixed it for good

**Comment by sheaf** [comment] 2020-05-15 19:18
Unfortunately I think my fix isn't right at all, here's another case that currently hangs the highlighting

```haskell
data A 

xxxxxxxxxxxxxxxxx Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb |
  ( Dddddddddddddddddddddddddd ( Eeeeeeeeeeeeeeeeeeeeeeeee fffffffffffffffffffffffff )
    ( Eeeeeeeeeeeeeeeeeeeeeeeee Fffffffffffffffffffffffff |
      ( Gggggggggggggggggggggg ( Aaaaaaaaaaaaaaaaaaaaa bbbbbbbbbbbbbbbbbbbbbbb, cccccccccccccccccccccccc )
        ( Dddddddddddddddddddddddddddd eeeeeeeeeeeeeeeeeeeeeeeeee |
          ( Hhhhhhhhhhhhhhhh iiiiiiiiiiiiiiiii )
        )
      )
    )
  )
xxxxxxxxxxxxxxxxx Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb |
  ( Dddddddddddddddddddddddddd ( Eeeeeeeeeeeeeeeeeeeeeeeee fffffffffffffffffffffffff )
    ( Eeeeeeeeeeeeeeeeeeeeeeeee Fffffffffffffffffffffffff |
      ( Gggggggggggggggggggggg ( Aaaaaaaaaaaaaaaaaaaaa bbbbbbbbbbbbbbbbbbbbbbb, cccccccccccccccccccccccc )
        ( Dddddddddddddddddddddddddddd eeeeeeeeeeeeeeeeeeeeeeeeee |
          ( Hhhhhhhhhhhhhhhh iiiiiiiiiiiiiiiii )
        )
      )
    )
  )
xxxxxxxxxxxxxxxxx Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb |
  ( Dddddddddddddddddddddddddd ( Eeeeeeeeeeeeeeeeeeeeeeeee fffffffffffffffffffffffff )
    ( Eeeeeeeeeeeeeeeeeeeeeeeee Fffffffffffffffffffffffff |
      ( Gggggggggggggggggggggg ( Aaaaaaaaaaaaaaaaaaaaa bbbbbbbbbbbbbbbbbbbbbbb, cccccccccccccccccccccccc )
        ( Dddddddddddddddddddddddddddd eeeeeeeeeeeeeeeeeeeeeeeeee |
          ( Hhhhhhhhhhhhhhhh iiiiiiiiiiiiiiiii )
        )
      )
    )
  )
xxxxxxxxxxxxxxxxx Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb |
  ( Dddddddddddddddddddddddddd ( Eeeeeeeeeeeeeeeeeeeeeeeee fffffffffffffffffffffffff )
    ( Eeeeeeeeeeeeeeeeeeeeeeeee Fffffffffffffffffffffffff |
      ( Gggggggggggggggggggggg ( Aaaaaaaaaaaaaaaaaaaaa bbbbbbbbbbbbbbbbbbbbbbb, cccccccccccccccccccccccc )
        ( Dddddddddddddddddddddddddddd eeeeeeeeeeeeeeeeeeeeeeeeee |
          ( Hhhhhhhhhhhhhhhh iiiiiiiiiiiiiiiii )
        )
      )
    )
  )
```

Adding an equals sign after `data A` will cause a problem.

I'm having some difficulties specifying the intended behaviour in the regex. I want to say "stop trying this regex once you are sure you won't be able to match even after extending the ending", but I am finding it difficult to do that while preserving other desirable properties (particularly multiline highlighting and allowing intervening comments).

**Comment by sheaf** [comment] 2020-05-15 19:33
By the above comment I mean that we can add `(?!\G)` as an alternative at the end of the end regex, which will ensure we stop trying to match as soon as we have come across non-matchable code. This definitely works to prevent the catastrophic backtracking, but it also disables correct highlighting for:

```haskell
data A =
  A B c
```
and

```haskell
data A = {- ... -} A B c
```

**Comment by sheaf** [comment] 2020-05-15 20:33
I went for a different approach: write an explicit failure condition, that says "no point in trying further, just give up now". That has at least fixed the issues reported above. I'm closing the ticket for now, please reopen if other issues manifest themselves.

**Comment by hexahedria** [comment] 2020-06-22 16:57
I think I've run across another instance of this. Running syntax highlighting for the line
```
data Foo a = (:>) Bar a deriving (Show, Ord)
```
hangs forever at
```
@@scanNext 12: | (:>) Bar a deriving (Show, Ord)\n|
```
and a debugger indicates that it's hanging at `findNextMatchSync` for [this rule](https://github.com/JustusAdam/language-haskell/blob/75aa09b5debfabc7ca5ecf9c37850c3623b8ca81/syntaxes/haskell.YAML-tmLanguage#L1007). This happens both on the released version and on `master`.

**Comment by sheaf** [comment] 2020-06-22 17:50
@hexahedria Thanks for the bug report, for the simple reproducer, and for checking on `master`. On my end it doesn't hang forever, but it slows down significantly and also produces incorrect highlighting.    
I'm looking into it.

**Comment by sheaf** [comment] 2020-06-22 18:22
Turns out there was a silly typo in the regular expression for data constructors (see 05bfeff).    
Fixed now, with some extra tests. @hexahedria let me know if you run into any further issues. Thanks again!

**Closed by sheaf** 2020-06-22 18:22 UTC
Labels: bug, priority:high

**Comment by hexahedria** [comment] 2020-06-22 23:05
Thanks for the quick fix!
