### ISSUE TITLE
Labels (OverloadedLabels extension) are not highlighted properly

### ISSUE THREAD

**Issue by poscat0x04** [JustusAdam/language-haskell#109] opened 2020-04-08 23:59 UTC
![image](https://user-images.githubusercontent.com/53291983/78844210-b5cb2200-7a37-11ea-8eeb-d7989d5ed5aa.png)

**Comment by JustusAdam** [comment] 2020-04-21 17:26
Duplicate of #68

**Closed by JustusAdam** 2020-04-21 17:26 UTC
Labels: bug, easy fix
