### ISSUE TITLE
Top level definitions not highlighted when type signature starts on next line

### ISSUE THREAD

**Issue by tomsmalley** [JustusAdam/language-haskell#27] opened 2017-06-25 14:52 UTC
<img width="188" alt="screen shot 2017-06-25 at 15 50 59" src="https://user-images.githubusercontent.com/4387499/27517095-24aaa44a-59be-11e7-848b-fdaab37b4bbb.png">

This is common with haddock markup as shown above.

**Comment by JustusAdam** [comment] 2017-06-26 10:13
It does work so long as you have the double colon on the first line.
So.
```haskell
works :: Int 
      -> IO ()
```

If you notice the github markup has the same limitation.

```haskell
doesn't_work 
    :: Int 
    -> IO ()
```
The reason for this is that the highlighting detection is done by line based regexes instead of a proper parser. 
It has some multiline support, but they aren't a straight forward CFG which makes it hard to implement patterns like these. Basically detection regexes always only work on a single line.
But it the double colon is on the next line there's no way to tell at the identifier that this is a type annotation.

I believe it may potentially be possible to implement this by capturing everything after a top level identifier and then pattern matching based on the separator (`::`, or`=`) but it is not simple.

I'll tag this issue with a wontfix for now because I believe fixing it is too much work for the time being and it is not as important of an issue.

**Comment by dktn** [comment] 2017-12-28 16:27
I'll be fine with an identifier left with a wrong color, but the type signature itself is very important, and it can be still matched if the line starts with `::`.

This style is really not uncommon, because it allows to use small, predictable 2 or 4 spaces indentations of long signatures.

You can see examples here: https://github.com/TaktInc/freer/blob/develop/src/Eff/Internal.hs

Also a formatting tool Brittany uses this style for longers type signatures: https://github.com/lspitzner/brittany

I just wanted to provide some evidence that the issue is not that unimportant as it seems to be.

**Comment by JustusAdam** [comment] 2017-12-28 23:42
Hmm, that may be an interesting point. I never thought especially handling the signature without the identifier.
It may even be possible to do it.

**Comment by JustusAdam** [comment] 2017-12-28 23:45
I just wish there was something like a parser generator or combinator library like Edward Kmett talked about where you build monoidal parsers. They are fast, incremental and would probably be strong enough to parse Haskell properly. Unlike the weird semi-parsers that these editors use.

**Comment by lierdakil** [comment] 2017-12-29 01:20
FWIW, we [struggle with this in Atom too](https://github.com/atom-haskell/language-haskell/issues/104), and there's no good way of fixing that with TextMate's grammar model, at least as far as I can tell.

It's possible to match this unambiguously:
```hs
someFunc
  :: String -> String
```
but this will fail miserably:
```hs
someFunc
  :: String
  -> String
```
reason for that being, it's possible to scope by indentation, but without backtracking, it's impossible to scope by indentation of already parsed lines. And here it actually depends on indentation of `someFunc` line, i.e. this is valid, if ugly, Haskell:

```hs
someFunc
    :: String
 -> String
```

Relevant issue on `brittany`: https://github.com/lspitzner/brittany/issues/94

Also, fun fact, GitHub uses Atom's Haskell grammar, hence it has the same limitation.

**Comment by lierdakil** [comment] 2017-12-29 01:41
Also, one thing to keep in mind is `ScopedTypeVariables`, which allows horrifying (for the grammar author) things like this:
```hs
f x = do
  stuff :: String <- x
  return ()
```
with usual indentation rules allowing even something like
```hs
f x = do
  stuff
    :: String
    -> String <- x
  return ()
```
And in the presence of `TypeOperators`, this can get even worse, f.ex.
```hs
f x = do
  stuff
    :: String
    ->> String
    --> IO String <- x
  return ()
data (->>) a b = DArr a b
data (-->) a b = DDArr a b
```
so matching on `->` as signature continuation is not a solution, not in the general case at least.

**Comment by dktn** [comment] 2017-12-29 15:03
Some common cases of signature continuation include `.` and `=>`. Also the context can be split in multiple lines like below:
```haskell
acquire
  :: forall res r s
   . ( s ~ Ancestor 0 r
     , Member (RegionEff res s) r
     )
  => ResourceCtor res
  -> Eff r (Resource res s)
acquire = acquire' thisRegion
```

(reformatted from https://github.com/TaktInc/freer/blob/develop/src/Eff/Region.hs)

**Comment by lierdakil** [comment] 2017-12-29 20:42
Weirdly enough, I managed to come up with a reasonably effective band-aid in https://github.com/atom-haskell/language-haskell/commit/bf554195c16dc3957347422050ee55880849a790 somehow

A terse explanation of how it works can be found in https://github.com/atom-haskell/language-haskell/issues/104#issuecomment-354497530

**Comment by JustusAdam** [comment] 2017-12-30 00:44
Actually thats not necessarily the problem.

Particularly the `do` block case is not so horrible, since we have `<-` that definitely terminates the type expression.
The same goes for the spread out contexts.
The crucial point is finding a start and an end for the entire type signature, and here the end in particular is tricky.

In fact is believe it is unsolvable.

The problem is that in order to determine whether the type expression is terminated we need the indentation level of the **previous** item, not the type expression itself.

In fact the following is beyond what the TextMate grammar can do.it cannot distinguish the to uses of `a`

```hs
f       :: Read a => String 
    -> a -- a is part of the type signature
f = show
g
        :: (Read a, Monad m) => String -> m
    a -- this is still type signature
g = return . read

class C m where

    h
        :: String -> m
    a :: Whatever -- a is now a new method
```

If we only have our start marker `::`, even if we record and use its indentation (which TextMate can) we end up with ambiguous definitions. Without knowing the indentation level of the binding itself, there is no way to terminate the type signature. And we cannot know the indentation of the binding, because we cannot use the binding as a start marker since it could be a naked top-level expression (thanks a lot `TemplateHaskell`) and because we can't  match more than one line to look it there's a `::`.

And btw i tested these definitions in GHCi, they do work ... (what a wonderfully weird language Haskell is ...)

All this impossibility stuff aside (maybe we should write a paper about it 😂). I think there's something we can do about your average type signature. So long as indentation (after `::` does not decrease) we can do reasonable things.

**Comment by JustusAdam** [comment] 2017-12-30 00:51
Btw @lierdakil I haven't used atom in a while, but did you guys take a look at the changes I made to make inline and multi-line type signatures here and add them to the atom grammar file?

**Comment by lierdakil** [comment] 2017-12-30 01:12
@JustusAdam, if you point me to relevant commits I will be able to say if we have something similar. Otherwise, I have only a vague idea of what you're talking about.

**Comment by lspitzner** [comment] 2017-12-31 11:05
Is there a centralized repository for text-mate style syntax definition for haskell? It seems somewhat like each editor has its own thing going (and adds a slight variation to the format used in case the inherent separation of different communities was not enough).

I came up with the same fix @lierdakil linked above. I understand that the syntax engine does not really allow to do the correct thing for any possible input, but it seems to be possible to create syntax definitions that work with most commonly used layouts. I would not count type signatures that move left of the `::` as commonly used.

(Also, type signatures seem to be easy compared to some other corners of haskell syntax. For example if one wanted to highlight all new "variable" binders introduced in haskell code, there are corner cases like

~~~~.hs
case 13 of x | Just ((+1) -> y) <- x + 1 -> y
--         ^                 ^
~~~~

(marked positions _introduce_ the relevant variables.)(and of course one is free to pepper some newlines into that one too.) I guess none of the different implementations/editors even attempt to highlight these introductions..)

**Comment by lspitzner** [comment] 2017-12-31 11:19
Not to say that supporting a different layout for type signatures is trivial. In the brittany issue there was the claim that this layout for type signatures could not be supported, and I just don't think that is true. Due to the weakness of the syntax detection engine one has to compromise, but those compromises seem to be a very general theme, not just for type signatures.

**Comment by lierdakil** [comment] 2017-12-31 11:23
Well, it can't be supported if you want to highlight the function name as well as type signature. I'm not a fan of compromises that reduce finctionality.

**Comment by lspitzner** [comment] 2017-12-31 11:40
At toplevel, or in the direct scope of a let or where, highlight an identifiers appearing alone in the line. One cannot separate declaration/definition:

~~~~.hs
foo
  :: Int
foo
  = 13
~~~~

but I think it is fine to highlight the function name in its definition too, so this is fine.
This requires to detect and keep track of the `let`/`where` contexts too, and you might not be doing that yet. Because we don't want to highlight

~~~~.hs
func = otherfunc
  argument -- this.
~~~~

I have implemented this and will publish it when ready (ScopedTypeVariables is annoying to support). I have based my stuff on top of the sublime-haskell syntax definition; haven't checked how that compares to the other syntax definitions.

**Comment by lierdakil** [comment] 2018-01-01 01:03
You can't decide what
```hs
foo
```
means because thanks to `TemplateHaskell` it might be a naked toplevel TH expression.

**Comment by JustusAdam** [comment] 2018-01-01 11:38
There is actually a branch here still where I attempted to highlight all created bindings `let`, `where`, in lambdas, as function arguments in `do` notation etc, etc. 
Apart from the fact that it is very difficult to do I also felt it didn't add much.
Haskell is a very terse language. In general things tend to be rather short. Plus it is immutable. As a result there are often quite a large number of bindings being introduced close to one another and highlighting them just makes it more confusing in my opinion because there's too much colourful stuff on the screen then.

**Comment by JustusAdam** [comment] 2018-01-01 11:39
If you want an editor with really good highlighting you should probably look at vim and emacs, they do let you define full custom parsers as I understand it.

**Comment by JustusAdam** [comment] 2018-09-01 17:35
Also a tip if you want to have this work, just leave the `::` on the line before, it should correctly parse the signature then. That is also the standard formatting applied by `hindent`.

**Closed by JustusAdam** 2018-09-01 17:35 UTC
Labels: bug, wontfix
